"""
Django settings for cms project.

Generated by 'django-admin startproject' using Django 4.2.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from pathlib import Path
from .base import *

DEBUG = True
os.environ.setdefault("START_ENV_TYPE", "dev")
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": "startdb",
        "USER": "root",
        "PASSWORD": "123456",
        "HOST": "127.0.0.1",
        "PORT": "3306",
    }
}

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.redis.RedisCache',
        'LOCATION': 'redis://127.0.0.1:6379',  # 'redis://username:password@127.0.0.1:6379',
    }
}

CELERY_BROKER_URL = "redis://127.0.0.1:6379/0"

ALLOWED_HOSTS = ['*']


