# Generated by Django 4.1 on 2023-09-19 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GitHubUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=100, verbose_name='用户名')),
                ('avatar_url', models.CharField(max_length=100, verbose_name='头像')),
            ],
            options={
                'verbose_name': 'GitHub用户信息',
                'verbose_name_plural': 'GitHub用户信息',
            },
        ),
        migrations.CreateModel(
            name='Repos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='仓库名称')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repos', to='demo.githubuser')),
            ],
            options={
                'verbose_name': 'GitHub用户信息',
                'verbose_name_plural': 'GitHub用户信息',
            },
        ),
    ]
